sudo: required
dist: xenial
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y dpkg g++ git make python3 python3-numpy python3-dev libgoogle-glog-dev verilator
    - git submodule update --init --recursive
script:
    - make -s -C nicotb/lib/cpp
    - make -s -C sim/UmiModel
    - make -s PY=python3 -C sim
branches:
    only:
        - master
